language: c
dist: precise

env:
    - SMVERSION=1.7
    - SMVERSION=1.8
    - SMVERSION=1.9

matrix:
    fast_finish: true
    allow_failures:
    - env: SMVERSION=1.7
    - env: SMVERSION=1.8
    - env: SMVERSION=1.9

before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib
    - sudo apt-get install lib32stdc++6

before_script:
    - wget -q "http://www.sourcemod.net/latest.php?version=$SMVERSION&os=linux" -O sourcemod.tar.gz
    - tar -xzf sourcemod.tar.gz
    - cd addons/sourcemod/scripting/
    - wget "https://raw.githubusercontent.com/KyleSanderson/SteamWorks/master/Pawn/includes/SteamWorks.inc" -o include/SteamWorks.inc
    - chmod +x spcomp
    - chmod +x compile.sh

script:
    - ./compile.sh materialadmin.sp ma_adminmenu.sp ma_basecomm.sp ma_checker.sp
