language: c
dist: precise

env:
    - SMVERSION=1.9
    - SMVERSION=1.10

matrix:
    fast_finish: true

before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib
    - sudo apt-get install lib32stdc++6

before_script:
    - wget -q "http://www.sourcemod.net/latest.php?version=$SMVERSION&os=linux" -O sourcemod.tar.gz
    - tar -xzf sourcemod.tar.gz
    - chmod +x git.sh
    - ./git.sh > addons/sourcemod/scripting/materialadmin.git.sp
    - cd addons/sourcemod/scripting
    - chmod +x spcomp
    - chmod +x compile.sh

script:
    - ./spcomp materialadmin.git.sp materialadmin.sp -omaterialadmin
    - ./spcomp materialadmin.git.sp ma_adminmenu.sp -oma_adminmenu
    - ./spcomp materialadmin.git.sp ma_basecomm.sp -oma_basecomm
    - ./spcomp materialadmin.git.sp ma_checker.sp -oma_checker
