name: Build and deploy

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.sm-version == '1.11.x' }}
    strategy:
      matrix:
        sm-version: [ '1.9.x', '1.10.x', '1.11.x' ]
        compiler-options: [ '', '__MADEBUG=1' ]
    
    env:
      BUILDS_URL: ${{ secrets.BUILDS_URL }}
      BUILDS_KEY: ${{ secrets.BUILDS_KEY }}
      DEBUG: ${{ contains(matrix.compiler-options, '__MADEBUG=1') }}

    name: "SM version ${{ matrix.sm-version }} ${{ matrix.compiler-options != '' && format('({0})', matrix.compiler-options) || '' }}"
    steps:
      - uses: actions/checkout@v2

      - name: Setup SP
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm-version }}
                      
      - name: Run compiler
        run: |
          cd addons/sourcemod
          mkdir plugins
          cd scripting
          curl -O https://raw.githubusercontent.com/CrazyHackGUT/sm-plugins/master/git.sh
          chmod +x git.sh
          ./git.sh > materialadmin.git.sp
          spcomp __GITHUB=1 materialadmin.git.sp materialadmin.sp -E -o ../plugins/materialadmin -iinclude ${{ matrix.compiler-options }}
          spcomp __GITHUB=1 materialadmin.git.sp ma_adminmenu.sp -E -o ../plugins/ma_adminmenu -iinclude -i${includePath}/.. ${{ matrix.compiler-options }}
          spcomp __GITHUB=1 materialadmin.git.sp ma_basecomm.sp -E -o ../plugins/ma_basecomm -iinclude ${{ matrix.compiler-options }}
          spcomp __GITHUB=1 materialadmin.git.sp ma_basevotes.sp -E -o ../plugins/ma_basevotes -iinclude ${{ matrix.compiler-options }}
          spcomp __GITHUB=1 materialadmin.git.sp ma_checker.sp -E -o ../plugins/ma_checker -iinclude ${{ matrix.compiler-options }}
      
      - name: Make artifact archive
        if: github.ref == 'refs/heads/master'
        run: |         
          if [[ "$DEBUG" == "true" ]]; then export CUSTOM_POSTFIX="d"; fi
          SMVERSION_FULL=${{ matrix.sm-version }}
          
          export SMVERSION_SHORT=${SMVERSION_FULL:0:-2}
          export ARCHIVE_FILENAME=sbma-newplugin.${GITHUB_SHA::7}.${SMVERSION_SHORT}${CUSTOM_POSTFIX}.tar.gz
          
          echo "ARCHIVE_FILENAME=$ARCHIVE_FILENAME" >> $GITHUB_ENV
          echo "SMVERSION_SHORT=$SMVERSION_SHORT" >> $GITHUB_ENV
          
          tar -cvf $ARCHIVE_FILENAME addons
      
      - name: Upload artifact to builds.kruzya.me
        if: github.ref == 'refs/heads/master'
        run: |
          if [[ "$DEBUG" == "true" ]]; then export ADDITIONAL_TAGS=",DEBUG"; fi 
          curl "${BUILDS_URL}?secret_key=${BUILDS_KEY}&tags=SourceMod%20${SMVERSION_SHORT}${ADDITIONAL_TAGS}" -F "artifact=@./${ARCHIVE_FILENAME}"